[tool.poetry]
name = "____project_name"
version = "0.1.0"
description = ""
authors = ["____author_name <____author_email>"]
license = "MIT"
readme = "README.md"
packages = [{include = "____project_name_identifier"}]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
langchain = "^____langchain_version"
pytest = "^7.4.0"
pytest-asyncio = "^0.21.1"
mypy = "^1.4.1"
ruff = "^0.0.278"
black = "^23.7.0"
openai = "^0.27.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
select = [
  "E",  # pycodestyle
  "F",  # pyflakes
  "I",  # isort
]
ignore = ["E501"] # line too long
